### ISSUE TITLE
Failed to execute script Main

### ISSUE THREAD

**Issue by b1n4Rhy** [sithis993/Crypter#72] opened 2020-05-01 02:03 UTC
Hi, I built Crypter with your _config_example.cfg_ config file. And I faced this problem when tried to execute the binary:

![](https://i.imgur.com/BpzXz78.png)

My environment:
- Python x86 ( I read the previous issue of GhostYWP )
- OS version: Windows 10 x64 - 10.0.19041 ( I built Crypter and tried to execute it on the same virtual machine)
- The Python packages were installed successfully via pip.

Can you help me? Great project, btw 👍 

-------------------

Edit: I used python 3.7.6 instead of 3.8.2. everything is okay now :D

**Comment by b1n4Rhy** [comment] 2020-05-01 02:10
oh, wait. Crypter is still running in the background

![](https://i.imgur.com/9e9pFV8.png)

Is this a bug or a feature ? 🤣

**Comment by sithis993** [comment] 2020-05-03 14:48
Hey, thanks! :-) is it all sorted now then? I should put something on the README about this really I don't think PyInstsller yet supports Python 3.8 which could have been the cause

**Comment by b1n4Rhy** [comment] 2020-05-03 18:43
Yeah, maybe your parameters of #Build Command (Line 285-290/BuilderThread.py) won't work on Python 3.8.2 . I tried some Googling but still can't figure it out why. :-(

**Comment by sithis993** [comment] 2020-05-04 08:15
Good to know! :-) I think it's just that PyInstaller, which is the tool used by the builder to actually create the ransomware exe, doesn't yet support 3.8:
![image](https://user-images.githubusercontent.com/22727993/80947139-6f26d880-8de7-11ea-9417-a587d0be4f2a.png)

Maybe I should add a check that warns the user if they're using Python 3.8 or higher.... I'll take a look at that I think

**Comment by sithis993** [comment] 2020-05-06 08:19
Just a quick update before I close this issue, I've added a check into the Builder in the latest release (3.4) to display an error if the user is running an supported version of Python:
![image](https://user-images.githubusercontent.com/22727993/81153295-ae396300-8f7a-11ea-8dda-86dad285dad2.png)

**Closed by sithis993** 2020-05-06 08:19 UTC
