### ISSUE TITLE
Fatal Error !

### ISSUE THREAD

**Issue by ozgursevgi** [sithis993/Crypter#32] opened 2017-10-13 12:47 UTC
Crypter.exe run but fatal error  "main returned -1 " 

[2017-10-13 15:41:40]: Build Launched
[2017-10-13 15:41:40]: DEBUG Level: 1 - Low
[2017-10-13 15:41:40]: Builder: Checking configuration...
[2017-10-13 15:41:40]: Builder: Checking builder_language
[2017-10-13 15:41:40]: Builder: Checking pyinstaller_aes_key
[2017-10-13 15:41:41]: Builder: Checking icon_file
[2017-10-13 15:41:41]: Builder: Checking upx_dir
[2017-10-13 15:41:41]: Builder: Checking encrypted_file_extension
[2017-10-13 15:41:41]: Builder: Checking wallet_address
[2017-10-13 15:41:41]: Builder: Checking bitcoin_fee
[2017-10-13 15:41:41]: Builder: Checking key_destruction_time
[2017-10-13 15:41:41]: Builder: Checking max_file_size_to_encrypt
[2017-10-13 15:41:41]: Builder: Checking filetypes_to_encrypt
[2017-10-13 15:41:41]: Builder: Checking ransom_message
[2017-10-13 15:41:42]: Builder: Checking debug_level
[2017-10-13 15:41:42]: Builder: Validation successful
[2017-10-13 15:41:42]: Builder: Creating binary runtime config at Resources/runtime.cfg
[2017-10-13 15:41:42]: Builder: Runtime config successfully written
[2017-10-13 15:41:42]: Builder: Creating PyInstaller SPEC file
[2017-10-13 15:41:42]: Spec: PyInstaller AES key provided. Script files will be encrypted
[2017-10-13 15:41:42]: Spec: PyInstaller binary Icon file specified. Custom icon will be added
[2017-10-13 15:41:42]: Spec: UPX Packer specified. UPX will be used
[2017-10-13 15:41:42]: Builder: SPEC file successfully created
[2017-10-13 15:41:42]: Builder: Calling PyInstaller. Please wait...
[2017-10-13 15:41:42]: PyInstaller: 46 INFO: PyInstaller: 3.1.1
[2017-10-13 15:41:42]: PyInstaller: 46 INFO: Python: 2.7.13
[2017-10-13 15:41:42]: PyInstaller: 46 INFO: Platform: Windows-10-10.0.15063
[2017-10-13 15:41:42]: PyInstaller: 93 INFO: UPX is available.
[2017-10-13 15:41:42]: PyInstaller: 93 INFO: Removing temporary files and cleaning cache in C:\Users\xxx\AppData\Roaming\pyinstaller
[2017-10-13 15:41:42]: PyInstaller: 125 INFO: Extending PYTHONPATH with paths
[2017-10-13 15:41:42]: PyInstaller: ['C:\\Users\\xxx\\Desktop\\Crypter-develop\\Crypter-develop\\Crypter',
[2017-10-13 15:41:42]: PyInstaller:  'C:\\Users\\xxx\\Desktop\\Crypter-develop\\Crypter-develop\\build\\build']
[2017-10-13 15:41:42]: PyInstaller: 125 INFO: Will encrypt Python bytecode with key: 0123456789ANCDEF
[2017-10-13 15:41:42]: PyInstaller: 125 INFO: Adding dependencies on pyi_crypto.py module
[2017-10-13 15:41:42]: PyInstaller: 125 INFO: checking Analysis
[2017-10-13 15:41:42]: PyInstaller: 125 INFO: Building Analysis because out00-Analysis.toc is non existent
[2017-10-13 15:41:42]: PyInstaller: 125 INFO: Initializing module dependency graph...
[2017-10-13 15:41:42]: PyInstaller: 125 INFO: Initializing module graph hooks...
[2017-10-13 15:41:42]: PyInstaller: 202 INFO: Analyzing hidden import 'Crypto.Cipher._AES'
[2017-10-13 15:41:43]: PyInstaller: 296 INFO: running Analysis out00-Analysis.toc
[2017-10-13 15:41:43]: PyInstaller: 296 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
[2017-10-13 15:41:43]: PyInstaller:   required by C:\Python27\python.exe
[2017-10-13 15:41:43]: PyInstaller: 406 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest
[2017-10-13 15:41:43]: PyInstaller: 406 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest
[2017-10-13 15:41:43]: PyInstaller: 406 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_f480bfaef65491a5.manifest
[2017-10-13 15:41:43]: PyInstaller: 406 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9279_none_f4810f46f6546fca.manifest
[2017-10-13 15:41:43]: PyInstaller: 625 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.30729.9279_none ...
[2017-10-13 15:41:43]: PyInstaller: 625 INFO: Found manifest C:\WINDOWS\WinSxS\Manifests\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9279_none_50939ec6bcb7c97c.manifest
[2017-10-13 15:41:43]: PyInstaller: 625 INFO: Searching for file msvcr90.dll
[2017-10-13 15:41:43]: PyInstaller: 625 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9279_none_50939ec6bcb7c97c\msvcr90.dll
[2017-10-13 15:41:43]: PyInstaller: 625 INFO: Searching for file msvcp90.dll
[2017-10-13 15:41:43]: PyInstaller: 625 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9279_none_50939ec6bcb7c97c\msvcp90.dll
[2017-10-13 15:41:43]: PyInstaller: 625 INFO: Searching for file msvcm90.dll
[2017-10-13 15:41:43]: PyInstaller: 625 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9279_none_50939ec6bcb7c97c\msvcm90.dll
[2017-10-13 15:41:43]: PyInstaller: 781 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest
[2017-10-13 15:41:43]: PyInstaller: 781 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest
[2017-10-13 15:41:43]: PyInstaller: 796 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_f480bfaef65491a5.manifest
[2017-10-13 15:41:43]: PyInstaller: 796 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9279_none_f4810f46f6546fca.manifest
[2017-10-13 15:41:43]: PyInstaller: 796 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9279)
[2017-10-13 15:41:43]: PyInstaller: 859 INFO: Analyzing ..\Crypter\Main.py
[2017-10-13 15:41:47]: PyInstaller: 4665 INFO: Processing pre-find module path hook   distutils
[2017-10-13 15:41:47]: PyInstaller: 4859 INFO: Looking for import hooks ...
[2017-10-13 15:41:47]: PyInstaller: 4859 INFO: Processing hook   hook-distutils.py
[2017-10-13 15:41:47]: PyInstaller: 4859 INFO: Processing hook   hook-encodings.py
[2017-10-13 15:41:48]: PyInstaller: 5266 INFO: Processing hook   hook-wx.lib.pubsub.py
[2017-10-13 15:41:48]: PyInstaller: 5610 INFO: Processing pre-safe import module hook   _xmlplus
[2017-10-13 15:41:48]: PyInstaller: 5799 INFO: Processing hook   hook-xml.py
[2017-10-13 15:41:49]: PyInstaller: 6368 INFO: Processing hook   hook-httplib.py
[2017-10-13 15:41:49]: PyInstaller: 6382 INFO: Looking for ctypes DLLs
[2017-10-13 15:41:49]: PyInstaller: 6382 INFO: Analyzing run-time hooks ...
[2017-10-13 15:41:49]: PyInstaller: 6398 INFO: Looking for dynamic libraries
[2017-10-13 15:41:49]: PyInstaller: 7195 WARNING: Attempted to add Python module twice with different upper/lowercases: Crypto.Util._counter
[2017-10-13 15:41:49]: PyInstaller: 7195 WARNING: Attempted to add Python module twice with different upper/lowercases: Crypto.Cipher._DES
[2017-10-13 15:41:49]: PyInstaller: 7195 WARNING: Attempted to add Python module twice with different upper/lowercases: Crypto.Util.strxor
[2017-10-13 15:41:49]: PyInstaller: 7195 WARNING: Attempted to add Python module twice with different upper/lowercases: Crypto.Hash._SHA256
[2017-10-13 15:41:49]: PyInstaller: 7195 WARNING: Attempted to add Python module twice with different upper/lowercases: Crypto.Cipher._DES3
[2017-10-13 15:41:49]: PyInstaller: 7195 WARNING: Attempted to add Python module twice with different upper/lowercases: Crypto.Random.OSRNG.winrandom
[2017-10-13 15:41:49]: PyInstaller: 7195 WARNING: Attempted to add Python module twice with different upper/lowercases: Crypto.Cipher._AES
[2017-10-13 15:41:49]: PyInstaller: 7195 INFO: Looking for eggs
[2017-10-13 15:41:49]: PyInstaller: 7195 INFO: Using Python library C:\WINDOWS\system32\python27.dll
[2017-10-13 15:41:49]: PyInstaller: 7195 INFO: Found binding redirects:
[2017-10-13 15:41:49]: PyInstaller: [BindingRedirect(name=u'Microsoft.VC90.CRT', language=None, arch=u'x86', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 9279), publicKeyToken=u'1fc8b3b9a1e18e3b')]
[2017-10-13 15:41:49]: PyInstaller: 7210 INFO: Warnings written to C:\Users\xxx\Desktop\Crypter-develop\Crypter-develop\build\build\Main\warnMain.txt
[2017-10-13 15:41:50]: PyInstaller: 7304 INFO: Appending 'datas' from .spec
[2017-10-13 15:41:50]: PyInstaller: 7304 INFO: checking PYZ
[2017-10-13 15:41:50]: PyInstaller: 7304 INFO: Building PYZ because out00-PYZ.toc is non existent
[2017-10-13 15:41:50]: PyInstaller: 7304 INFO: Building PYZ (ZlibArchive) C:\Users\xxx\Desktop\Crypter-develop\Crypter-develop\build\build\Main\out00-PYZ.pyz
[2017-10-13 15:41:50]: PyInstaller: 8007 INFO: checking PKG
[2017-10-13 15:41:50]: PyInstaller: 8007 INFO: Building PKG because out00-PKG.toc is non existent
[2017-10-13 15:41:50]: PyInstaller: 8007 INFO: Building PKG (CArchive) out00-PKG.pkg
[2017-10-13 15:41:50]: PyInstaller: 8023 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\msvcr90.dll
[2017-10-13 15:41:51]: PyInstaller: 8414 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\msvcp90.dll
[2017-10-13 15:41:51]: PyInstaller: 8664 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\msvcm90.dll
[2017-10-13 15:41:51]: PyInstaller: upx: C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\msvcm90.dll: CantPackException: .NET files are not yet supported
[2017-10-13 15:41:51]: PyInstaller: 8726 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9279)
[2017-10-13 15:41:51]: PyInstaller: 8726 INFO: Updating manifest in C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\python27.dll
[2017-10-13 15:41:51]: PyInstaller: 8726 INFO: Updating resource type 24 name 2 language 1033
[2017-10-13 15:41:51]: PyInstaller: 8743 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\python27.dll
[2017-10-13 15:41:53]: PyInstaller: 10320 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\unicodedata.pyd
[2017-10-13 15:41:53]: PyInstaller: 10743 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\bz2.pyd
[2017-10-13 15:41:53]: PyInstaller: 10820 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\crypto.util._counter.pyd
[2017-10-13 15:41:53]: PyInstaller: 10898 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\crypto.cipher._des.pyd
[2017-10-13 15:41:53]: PyInstaller: 10993 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\crypto.util.strxor.pyd
[2017-10-13 15:41:53]: PyInstaller: upx: C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\crypto.util.strxor.pyd: NotCompressibleException
[2017-10-13 15:41:53]: PyInstaller: 11054 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\_hashlib.pyd
[2017-10-13 15:41:54]: PyInstaller: 11726 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\crypto.hash._sha256.pyd
[2017-10-13 15:41:54]: PyInstaller: 11789 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\crypto.cipher._des3.pyd
[2017-10-13 15:41:54]: PyInstaller: 11882 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\crypto.random.osrng.winrandom.pyd
[2017-10-13 15:41:54]: PyInstaller: 11945 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\crypto.cipher._aes.pyd
[2017-10-13 15:41:54]: PyInstaller: 12023 INFO: Updating manifest in C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\wx._misc_.pyd
[2017-10-13 15:41:54]: PyInstaller: 12023 INFO: Updating resource type 24 name 2 language 1033
[2017-10-13 15:41:54]: PyInstaller: 12039 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\wx._misc_.pyd
[2017-10-13 15:41:55]: PyInstaller: 12460 INFO: Updating manifest in C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\wx._controls_.pyd
[2017-10-13 15:41:55]: PyInstaller: 12460 INFO: Updating resource type 24 name 2 language 1033
[2017-10-13 15:41:55]: PyInstaller: 12476 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\wx._controls_.pyd
[2017-10-13 15:41:55]: PyInstaller: 13070 INFO: Updating manifest in C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\wx._windows_.pyd
[2017-10-13 15:41:55]: PyInstaller: 13070 INFO: Updating resource type 24 name 2 language 1033
[2017-10-13 15:41:55]: PyInstaller: 13070 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\wx._windows_.pyd
[2017-10-13 15:41:56]: PyInstaller: 13539 INFO: Updating manifest in C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\wx._gdi_.pyd
[2017-10-13 15:41:56]: PyInstaller: 13539 INFO: Updating resource type 24 name 2 language 1033
[2017-10-13 15:41:56]: PyInstaller: 13539 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\wx._gdi_.pyd
[2017-10-13 15:41:56]: PyInstaller: 14132 INFO: Updating manifest in C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\wx._core_.pyd
[2017-10-13 15:41:56]: PyInstaller: 14132 INFO: Updating resource type 24 name 2 language 1033
[2017-10-13 15:41:56]: PyInstaller: 14164 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\wx._core_.pyd
[2017-10-13 15:41:57]: PyInstaller: 14929 INFO: Updating manifest in C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\wx._xrc.pyd
[2017-10-13 15:41:57]: PyInstaller: 14929 INFO: Updating resource type 24 name 2 language 1033
[2017-10-13 15:41:57]: PyInstaller: 14945 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\wx._xrc.pyd
[2017-10-13 15:41:57]: PyInstaller: 15085 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\pyexpat.pyd
[2017-10-13 15:41:58]: PyInstaller: 15233 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\_ssl.pyd
[2017-10-13 15:41:58]: PyInstaller: 16122 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\_socket.pyd
[2017-10-13 15:41:59]: PyInstaller: 16263 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\select.pyd
[2017-10-13 15:41:59]: PyInstaller: 16419 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\win32event.pyd
[2017-10-13 15:41:59]: PyInstaller: 16497 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\win32api.pyd
[2017-10-13 15:41:59]: PyInstaller: 16717 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\wxmsw30u_core_vc90.dll
[2017-10-13 15:42:04]: PyInstaller: 21909 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\wxmsw30u_adv_vc90.dll
[2017-10-13 15:42:05]: PyInstaller: 22542 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\wxbase30u_vc90.dll
[2017-10-13 15:42:06]: PyInstaller: 23714 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\wxmsw30u_html_vc90.dll
[2017-10-13 15:42:06]: PyInstaller: 24079 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\wxbase30u_net_vc90.dll
[2017-10-13 15:42:06]: PyInstaller: 24220 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\wxmsw30u_xrc_vc90.dll
[2017-10-13 15:42:07]: PyInstaller: 24605 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\wxbase30u_xml_vc90.dll
[2017-10-13 15:42:07]: PyInstaller: 24730 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\pywintypes27.dll
[2017-10-13 15:42:07]: PyInstaller: 24839 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9279)
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Bootloader C:\Python27\lib\site-packages\pyinstaller-3.1.1-py2.7.egg\PyInstaller\bootloader\Windows-32bit\runw.exe
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: checking EXE
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Building EXE because out00-EXE.toc is non existent
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Building EXE from out00-EXE.toc
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: SRCPATH [('C:\\pdf.ico', None)]
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Updating icons from ['C:\\pdf.ico'] to c:\users\xxx\appdata\local\temp\tmp7k_hds
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_GROUP_ICON 0 resource with 384 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 1 resource with 26184 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 2 resource with 14593 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 3 resource with 6048 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 4 resource with 1128 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 5 resource with 2440 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 6 resource with 4264 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 7 resource with 9640 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 8 resource with 16936 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 9 resource with 21640 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 10 resource with 38056 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 11 resource with 67624 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 12 resource with 1384 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 13 resource with 1736 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 14 resource with 2216 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 15 resource with 3752 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 16 resource with 5672 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 17 resource with 7112 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 18 resource with 11432 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 19 resource with 19496 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 20 resource with 296 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 21 resource with 488 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 22 resource with 744 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 23 resource with 1640 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 24 resource with 2664 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 25 resource with 3560 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 26 resource with 5864 bytes
[2017-10-13 15:42:08]: PyInstaller: 25605 INFO: Writing RT_ICON 27 resource with 10344 bytes
[2017-10-13 15:42:08]: PyInstaller: 25620 INFO: Executing - C:\upx394w\upx --lzma -q C:\Users\xxxx\AppData\Roaming\pyinstaller\bincache01_py27_32bit\tmp7k_hds
[2017-10-13 15:42:08]: PyInstaller: 25761 INFO: Appending archive to EXE C:\Users\xxx\Desktop\Crypter-develop\Crypter-develop\build\dist\Main.exe
[2017-10-13 15:42:08]: Build successful
[2017-10-13 15:42:08]: Crypter exe written to 'C:\Users\xxxx\Desktop\Crypter-develop\Crypter-develop\bin\Crypter.exe'

**Comment by sithis993** [comment] 2017-10-13 12:50
Looks like there's a few people running into this problem. Currently investigating! I'll add another comment once I know what's going on. Apologies

**Comment by sithis993** [comment] 2017-10-13 13:47
Okay... I think I've figured out what the problem is! Can you try rebuilding but DONT use UPX. Leave the "UPX Packer Directory" field blank. I think there's some kind of strange issue with UPX at the moment. Can you let me know if this makes a difference? thanks

**Comment by ozgursevgi** [comment] 2017-10-13 15:10
ok worked problem upx thanks

-Windows xp 32 bit is working but enter decryption key 
"AppName: crypter.exe	 AppVer: 0.0.0.0 ModName: wxbase30u_vc90.dll
 ModVer: 3.0.0.0	 Offset: 00069602"

- Only the files on the desktop are encrypted, other directories are not affected (Network, c, d, usb)

**Comment by sithis993** [comment] 2017-10-13 15:22
Nice! I'll add a warning about this until I can figure out exactly why UPX is causing this problem.

Sorry, I don't quite understand what you mean. Are you getting a problem when you try to enter the decryption key?

Yes that's correct. So at the moment, only files in the following directories are encrypted:

- [USER_HOME_DIR]\Desktop
- [USER_HOME_DIR]\Documents
- [USER_HOME_DIR]\Downloads
- [USER_HOME_DIR]\Music
- [USER_HOME_DIR]\Pictures
- [USER_HOME_DIR]\Videos

I'm going to add more very soon so that it will encrypted other drives too. I just didn't do this at the time because I knew it would be quite easy to do in the future.

In the meantime, if you really need to encrypt other specific locations, you can add more to the _base_dirs_ list in the _get_base_dirs()_ method which is in [Base.py](https://github.com/sithis993/Crypter/blob/master/Crypter/Base.py).

Once you've done that, just rebuild the exeuctable using the Builder :-)

**Comment by ozgursevgi** [comment] 2017-10-13 15:27
ok understand thanks

**Comment by sithis993** [comment] 2017-10-13 21:58
What do you mean by network shared files?

**Comment by sithis993** [comment] 2017-10-13 22:37
I've also identified a solution for the problem you mentioned here:

"AppName: crypter.exe	AppVer: 0.0.0.0 ModName: wxbase30u_vc90.dll
ModVer: 3.0.0.0	Offset: 00069602"

See issue #34 . I have a solution for this and am implementing it at the moment :-). It's because there is an issue with wxPython 3.0.0.0. Using version 3.0.2.0 will solve this

**Comment by sithis993** [comment] 2017-10-13 23:04
So the two problems you had have now been solved and if you download the new Crypter_distributable_2.0.zip from the [2.0 Release](https://github.com/sithis993/Crypter/releases/tag/2.0), you should be able to use UPX , and the "Enter Decrytion Key" button will also work.

Make sure to install the new wxPython exe that's in the dependencies folder

**Comment by sithis993** [comment] 2017-10-17 22:24
Closing issue as this and the relevant "sub-issues" have been fixed

**Closed by sithis993** 2017-10-17 22:24 UTC
