### ISSUE TITLE
failure to execute script main

### ISSUE THREAD

**Issue by sleekmike** [sithis993/Crypter#53] opened 2018-04-06 14:13 UTC
hello, i tried everything and it worked and created the crypter.exe file in Bin directory but when i try opening the file i am getting the error "failure to execute script main". By the way i  tried this with version 2,40. thanks

**Comment by sithis993** [comment] 2018-04-06 14:56
Sorry to hear you're having issues. What's the file size of the .exe file that is produced? also, rather than double clicking the Crypter .exe to launch it, can you run it using a Git Bash terminal (You'll need to download [Git](https://git-scm.com/download/win) if you don't have it downloaded already).

This will give you the full Python traceback, rather than just the "failed to execute script main" that PyInstaller returns, which will be of a lot more help in identifying the issue :-)

Thanks

**Comment by sleekmike** [comment] 2018-04-06 18:50
The size is about 4mb and I had to use latest version of pyinstaller to run it, I have Git desktop if that's what you recommend.

**Comment by sithis993** [comment] 2018-04-06 19:04
You'll need Git Bash I'm afraid as that's the only way I know of getting the .exe output when an error occurs (the traceback). 4MB doesn't sound quite right, which suggests some of the dependencies _might_ be missing from the .exe.

Did you install all of the dependencies from the [2.40 zip file](https://github.com/sithis993/Crypter/releases/download/2.40/Crypter_distributable_2.40.zip). I bundle everything up this way because the versions of each dependency are quite specific. If you start with a fresh environment and install these you can be confident that you have exactly what's needed. You then shouldn't be hitting any errors.

The developers of wxPython, PyInstaller etc. love to change things, and there are always some fundamentl differences between versions, which often breaks things.

**Comment by sleekmike** [comment] 2018-04-06 23:46
Thanks a lot for your prompt response. I think its probably because i used the latest version of pyinstaller and other dependencies. i will try out this zipped file now and will get back to you ASAP. i will also get Git bash to see how it goes. Thanks

**Comment by sleekmike** [comment] 2018-04-09 19:15
So the program compiled as its suppose to but when i clicked on crypter.exe it gives me the error "fatal error- main returned -1. Also when i ran the program on Git bash i got the following error:

Traceback (most recent call last):
  File "<string>", line 437, in <module>
  File "<string>", line 65, in __init__
  File "<string>", line 333, in find_files
UnicodeDecodeError: 'ascii' codec can't decode byte 0xae in position 50: ordinal not in range(128)

**Comment by sithis993** [comment] 2018-04-10 08:06
That's awesome! This gives me something to work with :-) will take a look
at this a bit later today

пн, 9 апр. 2018 г., 20:15 sleekmike <notifications@github.com>:

**Comment by sithis993** [comment] 2018-04-10 09:36
I've just ran a brief test but haven't yet identified the issue. I suspected it would be because there were none-ASCII characters in a filename somewhere which were breaking the filename checks, but I've just tested with some Cyrillic characters and it seemed to handle it okay.

Hopefully you don't mind waiting as I can't look at this in-depth right this second. I'll take a look later tonight (It's currently 10:30AM where I am). Should be a pretty easy fix once I've identified the problem.

Thanks a lot for helping me to troubleshoot this. A lot of the time people post issues without output, so I no idea where to even begin looking! the traceback will help massively.

**Comment by sithis993** [comment] 2018-04-10 21:58
Is your machine in a different language other than English? Do you know if you have files on your machine with non-english chars in them? I'm struggling to hit this issue at the moment so it might take me a little longer to get to the bottom of it

**Comment by sleekmike** [comment] 2018-04-12 00:13
I'm using windows 7 English and all files in my computer are English characters. Thanks

**Comment by sithis993** [comment] 2018-04-13 21:49
Hi Mike,

I'm going to add a temporary fix in for you so you can at least get Crypter working. Will let you know when it's done

**Comment by sithis993** [comment] 2018-04-13 23:52
Hi Mike,

I've fixed this problem and created another release ([2.41](https://github.com/sithis993/Crypter/releases)) which contains the patch. It's not a particularly major change so you can just repull your branch to get the update.

Then just rebuild Crypter.exe using the GUI and run the new binary that gets created. Everything should run smoothly :-). Sorry it took a day or so. Let me know how it goes!

**Comment by sleekmike** [comment] 2018-04-14 00:47
ok thanks bro, i will try it out right away and i will give you feedback ASAP.

**Comment by sleekmike** [comment] 2018-04-14 14:42
Hi Sithis,
I did exactly as you said, it complied fine but when i ran the program i get "This file is corrupt and cannot be opened"
I tried running it on bash but i got the same thing  "This file is corrupt and cannot be opened".

**Comment by sithis993** [comment] 2018-04-14 14:57
Does the error message look like this?
![image](https://user-images.githubusercontent.com/22727993/38769536-8eaa15ea-3ffc-11e8-97b3-d1bef2673f36.png)

**Comment by sithis993** [comment] 2018-04-14 15:29
I suspect it is. This behaviour is actually completely intentional :-) This should mean you have it working! Let me explain what happens. 

Every time Crypter.exe runs it creates a Mutex to make sure that only _one_ instance can run at any one time. This is so that whilst Crypter is busy encrypting files, the user can't open the exe again and have two (or more) copies encrypting files simultaneously. If this did happen, then the user could run into all kinds of problems, which would ultimately mean that they couldn't get their files back. Make sense?

Now onto the error message: If Crypter.exe runs and there is already another instance running, then I purposely display this error message. When I added this functionality, I had a social engineering use case in mind. 

Let's say you send an Email to someone with Crypter.exe attached. They open it and run the exe, but from what they can see, nothing is happening. What they don't know is that in the background the encrypting operation is encrypting all of the files on the machine. What do you think the user will do first? they will try to open the exe again. Now if I didn't have the Mutex, another instance of Crypter would begin encrypting files, which is why I added the Mutex functionality. This error message is there so that a user would see it and assume that the file was broken and carry on with their day. Thus, there isn't really an error... It was done intentionally to minimise suspicion and increase the likelihood of the encryption operation finishing without the user interrupting it.

So if you're getting this, don't worry. Click OK, then open Task Manager and see if there is already a Crypter.exe process running :-)

**Comment by sleekmike** [comment] 2018-04-14 19:48
Yeah, that's exactly how it looks like.

**Comment by sleekmike** [comment] 2018-04-14 19:52
Ok that's really a clever thing to do, i will get back to you, once I confirm it works. Thanks

**Comment by sleekmike** [comment] 2018-04-15 00:34
I think I made the mistake of creating to separate crypters because i thought it was a compilation error from the first one and i checked my task manager and i saw two separate cryper.exe running.I have ended both processes but I have not seen any evidence of crypting so far. SO please what do i do now?

**Comment by sithis993** [comment] 2018-04-15 09:01
Hmm I think you might have ended the process during encryption. The reason you're seeing two processes is because of the way PyInstaller executables run. If you compile Python code into an executable and then run that executable, there are always two processes (for PyInstaller exe's at least)

I'm not sure of the exact details, I just know this is expected behaviour and you haven't actually opened it twice (remember, the Mutex won't let you run more than one instance anyway!)

I suspect it probably was encrypting files when you killed it. I usually starts with the AppData folder, so you might have ended the process before it could get to any of the common directories like Downloads, Documents, Pictures etc.

It sounds to me like it's actually working! Try running it again, and then leave it. Depending upon your machine and how many files you have, it may take a while. Nevertheless, after the encryption has finished the GUI should appear.

If it still hasn't appeared after 20 minutes, check your Downloads, Documents, Picture, Music etc. folders to see if any files in there look like they've been encrypted. It will probably still be running

**Comment by sleekmike** [comment] 2018-04-16 02:26
Hi Sithis,
It is actually working! i checked appdata just as you said and i found some locked files, i think i killed the process just as you said. you are the man!

**Comment by sleekmike** [comment] 2018-04-16 13:11
Hi Sithis, 
I can see some files are locked already but it's taking too long to lock files and the GUI for unlocking has not come up yet, must all the files be encrypted before it comes up?
Please how can I get file size of the crypter down?
Can I have you email?

**Comment by sithis993** [comment] 2018-04-16 19:40
Hi Mike,

How long has it taken? has the GUI appeared yet? it usually doesn't take toooo long... but of course that's completely dependent on how powerful your CPU is, as well as how many files it's encrypting.

How big is the file currently? If you use the [UPX Packer](https://upx.github.io/) you should be able to build it at around 7MB. I don't think it's possible to get it any lower though... This is because of the way PyInstaller builds the exe and bundles the libraries. Bundling the wx library for example (which is used for the GUI) adds around 2-3MB filesize.

I've been tempted to add some kind of _stealth_ mode that you can select in the builder. This would ignore the GUI and not bundle the wx library. The ransom note would then be displayed in a simpler form, i.e. setting the desktop background, opening a notepad document with it in etc. 

You can Email me at sithis9993@gmail.com :-)

**Comment by sleekmike** [comment] 2018-04-17 02:36
Hi Sithis,
Its, almost 2days now since it started crypting, nope the GUI has not yet surfaced! well i must admit my system is pretty slow and it has a lot of files scattered all over. its a 4GB ram and 2.1GHZ processor and about 250GB HDD which is almost full.

The file is about 9640KB. So to use UPX Packer i have to add to path when building a crypter right?
Also if Tkinker is used instead of WX Library would the EXE be smaller?

Well i think adding the stealth mode would really be a great idea, Please do  try to add this option ASAP, it would make the crypter more practical and useable.

Also if the crypter code was implemented in C/Cpp would the size of the crypter be smaller? and will it crypt files faster?

**Comment by sithis993** [comment] 2018-04-17 14:58
Hmm that is a long time indeed. I haven't seen it take that long before, but I've usually tested it on relatively decent hardware and haven't encrypted more than around 4K files or so. Given that you're only running on a 250GB hard disk, you probably don't have a huge number of files to encrypt as well.

There are only two areas that Crypter actually looks to encrypt: the user's home directory (The home directory of the user who runs the exe, such as C:\Users\Administrator) and all drives (excluding C:\) attached to the machine. These could be USB drives, network shares etc.

Can you take a look in the Downloads folder, Pictures etc. and see if there are locked files in there? Crypter encrypts the user directory in the alphabetical order in which the directory contents are listed, so it will start encrypting the user's _Downloads_ directory before their _Pictures_ directory for example. 

This is useful to know because you can sometimes check where Crypter is up to by starting with the AppData directory, and then moving through each directory until you hit something like Videos. When you hit a directory that doesn't contain .locked files, you know Crypter hasn't yet reached that location. Does that make sense? I'd suggest doing this so you can see how far Crypter has reached.

Yep that's correct. You'll need to download and extract UPX and then in the Builder select the extracted directory for the _UPX Packer Directory_, like so:

![image](https://user-images.githubusercontent.com/22727993/38877960-c5c528f0-4257-11e8-9441-c140b23afc22.png)

UPX should reduce the binary to around 7MB :-)

**Comment by sithis993** [comment] 2018-04-17 15:36
I'm not sure whether Tkinter would make the exe smaller or not. I know that wxWidgets uses the native GUI components, whilst Tkinter uses _some_ native components. In theory this should make a wx-based UI smaller to bundle, but Tk is so painful to use that I can't say I've ever built a GUI application in it... so I'm not entirely sure. Additionally, moving the GUI to Tk would likely require a rewrite of a few major components and would be no easy or quick task. 

Rewriting in C++ would most certainly mean a smaller binary (potentially much smaller). It might also make it quicker.... but probably not by a great deal. The speed of encryption is largely related to CPU speed, whilst the speed of reading and writing files is dependent upon the speed of the disk(s).

I have considered adding this _stealth_ option in the past, but whilst I'm still supporting this project and fixing bugs, I'm afraid that as of December 2017 I'm no longer actively developing Crypter. Consequently, I don't think this is something I can find time to do :-/. Without going into too much detail, I achieved my original goal with this project a while back, and was also advised that If I continued development I risk breaking some of the laws in my country. As a result I decided to move onto another project which I've been working on since.

**Comment by sleekmike** [comment] 2018-04-18 06:13
Hi Sithis,
I did just as u said and it got the Executable down to 7mb. The crypter finally finished encrypting files! and prompted the GUI window and i entered the key and it says "your files have been decrypted" but im looking around in different directories and files are still encrypted. Does it usually take long for complete decryption of files?

**Comment by sithis993** [comment] 2018-04-18 09:06
Hmm I suspect that _some_ files are still encrypted... but this will be from the first time you ran the exe and killed it. I didn't add anything in to get it to resume encrypting if the process was ended. Again, this is probably something that's worthwhile and I would put this in if I was still working on the project :-/. This would be useful if, for example, the user shut down the machine during encryption. Getting it to continue encryption after rebooting would certainly be useful... especially like in your case when encryption is taking so long. I'll keep this in mind if I ever start working on it again.

How many files did it say it had encrypted? Was it quite a lot? Once decrypted, all files should be accessible again. You'll know the decryption has completely finished when you see the following:

- The main GUI says "YOUR FILES HAVE BEEN DECRYPTED!"
- The progress bar is completely full
- The number of encrypted files is at 0 and it says (100%)

Yes I know what you mean about Tk, and you could be completely right. The reason I think wx is _likely_ to be smaller is because it uses the native GUI components. My understanding of this is that it means the components don't need to be bundled with the exe because wx just uses whatever is already on the system. However, Tk will need to bundle whichever components it uses which _aren't_ native to the OS.

No problem, thanks for helping me to resolve some important issues and also providing valuable feedback :-)

**Comment by sleekmike** [comment] 2018-04-18 11:39
yeah a lot of files are still encrypted. actually i ran the exe killed and since it gave an error i compiled another exe and tried it before reporting the issue of error "file is corrupted". so it took long to encrypt all the files. who when the GUI finally came up i tried to look at encrypted files from the GUI but it did not work so i entered the decryption key and i got the following: "YOUR FILES HAVE BEEN DECRYPTED!"
    The progress bar is completely full
    The number of encrypted files is at 0 and it says (100%)

so i looked around in the desktop and in appdata>local,roaming  there are still locked files.
I also checked the task manager crypter.exe stoped running so i restarted the system again i got the GUI i entered the key again and i got the same message as before. so i left the PC on for a while and still looked around the desktop and appdata folder to find files still locked.
Please what do i do to unlock the remaining files?

**Comment by sleekmike** [comment] 2018-04-18 11:43
Are all files suppose to instantly unlock if the decryption is successful? or do decryption work in the same fashion as encryption?

**Comment by sithis993** [comment] 2018-04-19 10:11
It sounds like it was running for a while the first time you executed and killed it, so there are probably quite a few files encrypted from the first run. The second time it ran and finished successfully is completely separate from the first run, so it won't decrypt files encrypted by the first run because it doesn't know about them.

When Crypter finishes encrypting, it writes out a list of encrypted files. This file is then used by Crypter so it knows where the files are that it needs to decrypt. The first time it ran you must have killed it before it had chance to write out this list of encrypted files. 

It's strange that it keeps opening when you reboot. When you click the decrypt files button, how many files does it say are encrypted? Yes all files should be decrypted as soon as it says the decryption is complete.

There's a chance that you wont be able to recover these files if you've decrypting them with the incorrect key. How many different keys do you have? (key.txt files)

**Comment by sleekmike** [comment] 2018-04-19 15:45
Well, it doesn't not give the number of encrypted files. When I try to view encrypted files I get an empty window saying "list of encrypted files not found" .
I have about different key from 3 different EXE's.
I think the problem is that IT doesn't know where encrypted files are. So each time I decrypt IT it just decrypts so fast, probably in a second. Please think of something I really need to unlock this files they are important files.

**Comment by sithis993** [comment] 2018-04-19 16:24
Eugh.. not good xD . Do you really need these files back? It's _reeeeaally_ not a good idea to run ransomware on a machine that you have data on that you need, which is why I put the following in the README:
![image](https://user-images.githubusercontent.com/22727993/39004002-0d747fc8-43f4-11e8-8ec8-5f52fd731fd0.png)

The first thing you need to do immediately is find the files that you _need_ to recover and back them up ASAP. Then get all of the keys from each key.txt file you have. Then you can answer the following:
- How many files do you need to recover?
- How many keys are there?

If you think you know which key.txt was used to encrypt the files then you've probably got a good chance of getting them back. Can you remember which Crypter.exe you ran the first time? (the time that it ran but you killed it before it could finish) the key.txt that was used to encrypt the files you can't recover will be in the same directory.

**Comment by sleekmike** [comment] 2018-04-19 17:00
Most of the files that I'm trying to recovery are in appdata, desktop and c:\. I'm sorry I have no way of knowing which key was used to encrypt the files, but if the first encryption was terminated as I reboot the pc then it's probably the second or 3rd exe I built that encrypted the files. Yeah I can remember the first key.txt I even wrote it down. Yeah I think I also found one key.txt in appdata or c:\ root folder, I'm not certain where I found it.

**Comment by sithis993** [comment] 2018-04-19 18:58
Well as you know, when Crypter encrypts files it writes the encryption key to key.txt. If you decrypt your files and run it again so that it re-encrypts, it doesn't actually use/create a new encryption key. It uses whatever's in key.txt (unless you delete this file, in which case it generates a new AES, writes it out to key.txt and uses it to encrypt files).

If you're not completely certain which key was used to encrypt those files then it's **crucial** that you back up those files. This is because what you'll need to do, is try decrypting those files with the key you think was used to encrypt them. 

If you get your files back then you know that you used the correct key. However, if after decryption the files have different contents but its still all giberish, then you've used the wrong decryption key. At this point you'll need to take the backups I told you to make, copy them so that they overwrite the ones you just tried to decrypt, and then use the next key you think it might have been.

You repeat this process until you find the correct key and get your files back, or you run out of keys to try. Does this make sense?

If it does then I'll explain how you can tell Crypter which files it needs to decrypt

**Comment by sleekmike** [comment] 2018-04-19 20:03
Yeah this make a lot of sense. But won't the  fact that I have tried different keys for decryption affect the files?
Please I would like to know how to tell crypter the files to decrypt.
I'm having about 4 keys now and 2 were create on 7th and the other two on 14th, the one found in user directory together with some locked files was created on 7th too.

**Comment by sleekmike** [comment] 2018-04-19 20:24
I've also observed that most of the locked files where modified and accessed from 14th onwards. I also found a few at the top of appdata directory that where modified and accessed on the 12th.I hope this information is useful for resolving this issue.

**Comment by sithis993** [comment] 2018-04-19 20:37
It definitely would. However, because Crypter was killed before it could write out the list of encrypted files, when you ran it successfully the second time and then decrypted it won't have decrypted the files you're now trying to recover because it didn't know about them. Crypter also doesn't encrypt .locked files. Consequently, they should have just been encrypted once, meaning that once decrypted with the correct key you should get your files back.

As long as you backup the encrypted files you're trying to recover, you should be fine. Like I said in my previous message, if you decrypt them with the incorrect key, you'll just need to overwrite them with the backups you're going to take, and then try the next key.

Right then... so onto how Crypter knows which files to decrypt: When Crypter starts it checks for the existence of a certain file, if this file exists then Crypter must have already been ran. This is how Crypter knows whether to start finding and encrypting files, or whether it just needs to display the GUI to the user. The file I'm talking about is the list of files that were encrypted and can be found at C:\Users\\<your_username>\AppData\Roaming\encrypted_files.txt

So that's how Crypter knows which files have been encrypted and which files should be decrypted when the user enters the decryption key. Each line in encrypted_files.txt is the absolute path of an encrypted file. What you'll need to do is add the absolute paths of the files you want to decrypt to that file.

For example, If I had a few files I wanted to decrypt, then the contents of C:\Users\\<my_username>\AppData\Roaming\encrypted_files.txt might look like this:

C:\Users\\<my_username>\Documents\cv.docx
C:\Users\\<my_username>\Documents\hello.pdf
C:\Users\\<my_username>\data.xls
C:\Users\\<my_username>\Pictures\me.jg

Once all of the files are in there that you want to decrypt, you can open the Crypter.exe and try to decrypt them using the key you think was used. If you click view encrypted files, you should see the data you just entered in encrypted_files.txt. Also, the number of encrypted files should have have increased to however many files you added

**Comment by sleekmike** [comment] 2018-04-19 21:08
Ok thanks a lot for your prompt response. Let me try everything that you have illustrated.

**Comment by sleekmike** [comment] 2018-04-19 23:58
i have tried all that you suggested, however i was only able to recover 2 files in the C:\Users\<my_username> directory.then i tried other files in asppdata, desktop and C:\  with different keys, each time overriding the existing files with files from my backup as you suggested. each time when i try to open a decrypted file i get an error message that the file is corrupted and cannot be opened. please what do I do from here?
Also what about the timing? if the files are not decrypted within the stipulated time (72HRS) do the files become corrupt and unreadable?

**Comment by sithis993** [comment] 2018-04-20 08:24
So for the two files that were recovered, they no longer have .locked extensions and their contents have been restored, is that right?

For the files that aren't being decrypted correctly, they no longer have the .locked extension but the content hasn't been restored correctly?

That seems a bit weird if that's the case.... the first time it ran it would have certainly encrypted more than two files, and those files _must_ have been encrypted with one of the keys that you have

Don't worry about the timer :-) It doesn't actually do anything as such. It says the key will be destroyed, but the key isn't destroyed and neither are the files. All that happens is the _Decrypt encrypted files_ and _View encrypted files_ buttons become disabled. To fix this you'll just need to run the builder again and create another crypter.exe with a longer time (It's set to 86400 by default with is 72 hours). The idea here was that the key would be sent to a remote server which would also have a timer mechanism on it to destroy the key after 72 hours. There is no remote server functionality right now though of course.

**Comment by sleekmike** [comment] 2018-04-20 11:48
Yes exactly, the .locked extension has been removed and  the two files content have been restored. By the way one of them is desktop.ini file.

**Comment by sleekmike** [comment] 2018-04-20 14:16
I've be tried all the keys for the files, using different crypter.exe to try each key, ive done all the combination that I can think off. Each time the .locked extension is being removed but the file still remains unreadable and not restored. Please what do I do know? Do you have like a master key oo something?

**Comment by sithis993** [comment] 2018-04-20 14:42
The Crypter.exe version you use shouldn't matter or anything, it's all about the encryption key. Have you definitely tried all of the keys you can find? the files shouldn't have been encrypted more than once so there should be a single key that will unlock them. I'm afraid there isn't a master key.

**Comment by sleekmike** [comment] 2018-04-20 14:55
Now if reboot my pc the GUI doesn't come up any longer, I have to click on the crypter.exe. Also why would any key I try remove the .locked extension and claim to decrypt the files, I though it's only the right key that should decrypt files and remove the .locked extension.

**Comment by sithis993** [comment] 2018-04-20 15:13
It can't work this way unfortunately. In it's most basic form, all an encryption algorithm does is take a bunch of bytes and convert them into a different bunch of bytes, and it does this one block at a time. If the block is incorrectly formatted then yes it can fail. However, if the block is correctly formatted then it can be encrypted/decrypted without a problem.

If the operation works without an exception, then this is considered a success as far as the program is concerned. How can it know that it successfully decrypted a PDF file? Maybe it wasn't a PDF file at all, but just had a .pdf extension. Maybe it was half of a PDF file, which couldn't open correctly anyway _before_ the encryption.

It's explained in the following diagram. The problem you have here however, is that when you decrypt with the incorrect key, you're essentially taking ciphertext and converting it into different ciphertext because the wrong key is used:
![image](https://user-images.githubusercontent.com/22727993/39058919-0fbe077e-44b5-11e8-9bab-73a6c78b3a6e.png)

Maybe check your recycle bin and see if there is a key.txt in there that you deleted but forgot about. I'm truly sorry I can't be of more help here :-/, but algorithms like AES are pretty solid. Working with malware - and ransomware in particular - is very dangerous, which is why I state in my README that this should only be done on a test machine where you don't care about the data.

**Comment by sleekmike** [comment] 2018-04-20 15:33
Ok thanks a lot, I will keep trying all the keys I can find. I don't think I decrypted with the wrong key initially because I had no idea of how to make crypter read the encrypted_file.txt, so all the keys that I was trying were in vain. Also I tried decrypted a .txt then wen I opened it, it had no content in it. Please may I have your functional email, I having been sending mails but no reply.

**Comment by sithis993** [comment] 2018-04-20 15:42
No problem. Did the .txt definitely have some content in it before the encryption ran? I haven't personally experienced any issues at all with decryption, at least where files contents isn't decrypted correctly. That _could_ be because the incorrect key was used but I'm not too sure.

That Email address is functional and I have seen the Emails, but usually before I reply I notice you've sent the same (or similar) message on here, so I usually end up replying here instead!

**Comment by sleekmike** [comment] 2018-04-20 18:51
Yes the file has contents in it. May be that could be the case. But I did the back up as you said and I'm trying different key on a new file each time. But could it be the initial time I  tried the keys when the crypter was not able to locate encrypted_files.txt ?

Ok I thought you were not getting the messages.

**Comment by sleekmike** [comment] 2018-04-22 16:12
Hi Sithis,
I've been wondering since the crypter encrypts file by shifting bytes and decrypts by moving bytes, if a wrong key was used to decrypt a file can somthing be done to take the file to its previous state before the wrong decryption.
Also if I try some keys on some files e.g txt files the file becomes empty (0kb) when I open them.

**Comment by sleekmike** [comment] 2018-04-22 22:34
Hello, I just tried encrypting some files with crypter on the same pc in question, however after decrypting it with the right key I still can't access the contents of the files. They are either gibberish or corrupted so there is something fundamentally wrong with crypter or maybe it's my pc, what do you think?

**Comment by sithis993** [comment] 2018-04-23 08:11
Hi sorry for slow response, I've been quite busy this weekend. I will give you a full response a little later

**Comment by sithis993** [comment] 2018-04-23 13:17
Hi Mike,

Regarding restoring the files to a previous state. I don't think this would be feasible. Let's say you encrypted 50GB of files on a machine, and you then try to decrypt them. In order to restore them to their _encrypted_ state you'd need to backup 50GB of encrypted files so they could be reverted if an incorrect key was used. So 50GB of files would become 100GB (50GB decrypted, 50GB encrypted so the user could revert). It's certainly possible.. just not quite sure it would be the right approach. I've thought of a better approach where Crypter could do what you asked for earlier; check the decryption key is correct before trying to decrypt any files. I wasn't sure this was possible, but I think it would be if Crypter did the following:

1. Generate AES key
2. Encrypt a pre-defined hardcoded string, like "hello world" and store it somewhere
3. Encrypt any files found on disk with the same key
4. Present the GUI

Then, when the user enters a decryption key we use that key to first decrypt the encrypted "hello world" string. If the string decrypts correctly to be "hello world", then we know we've got the correct key and can start decrypting files . This is my bad.... I probably should have realised this approach as it's _probably_ how other tools verify encryption keys for encrypting/decrypting data. As mentioned, I'm not actively developing Crypter but I _may_ take a look at implementing this.

**Comment by sithis993** [comment] 2018-04-23 13:27
I think here Crypter could be made a little more intuitive as I suspect a lot of problems you're having are as a result of Crypter being killed the first time it ran (that's the only thing I can put it down to at least). Rather than writing out the list of encrypted files _after_ all files have been encrypted, it should probably do this each time a file is encrypted. This way if Crypter is killed prematurely, it will know which files it was able to successfully encrypt before it was interrupted. The only problem here is this will mean Crypter takes longer when encrypting files. How much longer depends on the machine specs and disk IO

**Comment by sleekmike** [comment] 2018-04-23 14:40
Hello Sithis,
Firstly please if there is any way I can try to restore my files, I will be very more than willing to try it. I can use an external HDD to back up my files if the need be.
I think you should definitely try to add the verification functionality if you ever resume work on crypter.

Secondly, I must admit I tried running crypter several times and killing it in the task manager, because it took so long(days) before I could notice any evidence of encryption, and I'm sure this could be the root of the problem that I'm experiencing. But most of my files are still in .locked extension so I think they maybe be still recoverable.
Also i noticed that the crypter was running yester , I probably ran it by mistake when I was trying to try decryption keys and it encrypted files in My documents and appdata and other places that it had not encrypted, I let it run finished and after that The GUI came up and I viewed encrypted files list this time and it came up. I cautiously copied the encrypted file list in roaming folder and saved it somewhere, after that I copied some newly encrypted files and tried the key found in crypters directly but the files where not readable. That's why I'm wondering if the problem is from my system or crypter.

**Comment by sleekmike** [comment] 2018-04-23 15:52
Also when building one of the crypter I used, I changed a key in the pyinstaller_AES_ key " ". I just checked my configuration files now, while in some other configuration file i was empty and in some it contained the default "123456789ABCDEF". I hope this could be of help.

**Comment by sithis993** [comment] 2018-04-23 16:13
Firstly I'd recommend creating and using a virtual machine for any further testing you're going to do. This will make it easier for you to revert to specific states and help you to avoid encrypting any more of your own files. If you don't have access to something like VMware, [VirutalBox](https://www.virtualbox.org/) is free (apologies if you already know all of this). You might need to do this on another physical machine however given how low on disk space you are.

If you use a VM then you can take snapshots before encryption/decryption, and then revert the snahpshot if things don't quite work. You'll then have a fresh instance to test decryption on. You could copy your encrypted files onto this machine and then run through all of the keys you have again.

If your files have a .locked extension then, as I mentioned before, they should have only been encrypted once. This means you'll only need to find the right key . Start on your most important files. Most of the contents of AppData won't be personal data that you need to keep, and usually just consists of temp program files and configuration.

Other than this I'm afraid I don't have any more ideas. AES is pretty strong encryption and you can't realistically decrypt without the correct key.

If you're happy to do so you could send me a link to one of the encrypted files you can't recover, as well as all of the keys you've tried. I can then test this on my machine and see if I'm able to decrypt it. Obviously doesn't need to be anything with personal data in.

**Comment by sleekmike** [comment] 2018-04-23 21:04
I have virtualbox on my PC, its because of low disk space that I ran crypter on my PC. But I have gotten an external HDD to free up space on my PC so that I can use virtualbox for any further testing of crypter. 

Honestly I'm so elated about your suggestion because it was the next thing that I wanted to ask of you, I'm glad that you are willing to go this far just to help me get my files back . I will send a link to you right away. Thanks a lot you are the man!

**Comment by dsaplbg** [comment] 2018-06-11 14:38
Hi i got same error "Failed to execute script Main", all dependencies are installed correctly but still got same error.
![untitled-2](https://user-images.githubusercontent.com/5876671/41238237-20e16c82-6d9e-11e8-9268-38fb7fb68282.jpg)

Any suggestion ? The OS is Windows 7 32 bit.

**Comment by dsaplbg** [comment] 2018-06-11 14:48
i've got error that missing module publesher but after pip install is still the same 
![untitled-12](https://user-images.githubusercontent.com/5876671/41238839-a051fd96-6d9f-11e8-841b-26a153a4a24e.jpg)

**Comment by dsaplbg** [comment] 2018-06-11 15:55
Ok, fixed :)
I just cpied file from \wx-3.0-msw\wx\lib\pubsub\core\kwargs
to \wx-3.0-msw\wx\lib\pubsub\core

and it works.

**Comment by sithis993** [comment] 2018-06-12 05:21
Aha! Nice to see you've already tried the troubleshooting steps ;-) sorry
you're hitting issues though. That definitely looks like you've got the
wrong version of wxPython installed. Can you check this? After a certain
version of wxPython they basically changed the name of the publisher to
Pub, or something like that. I can't remember the exact details but that's
definitely a wxPython version issue. Are you definitely running the version
from the dependencies folder?

Thanks,
Sithis

**Closed** 2018-08-29 16:13 UTC
