### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Dontmindmes** [sithis993/Crypter#31] opened 2017-10-13 03:16 UTC
https://gyazo.com/b04eb4c29b13022afa3b94e8b056f9c8

Encryption Happend but it faild to open the window

**Comment by sithis993** [comment] 2017-10-13 08:07
Hey! So the first thing the ransomware does is the encryption. Once that's complete it tries to open the GUI. So given that the encryption has run, the GUI must be what's causing the issue.

These kinds of problems are my number one priority right now, so you have my undivided attention, lol. Have you got Git installed on your machine right now? if so, do you have Git BASH? Git BASH seems to catch the errors whilst windows CMD and Powershell don't

If you open Git BASH, go to the bin directory that has the Crypter.exe executable in it, and run ./Crypter.exe. Then once you click OK on that "Fatal Error!" error box, you should get the error printed to the console :-)

**Comment by sithis993** [comment] 2017-10-13 13:46
Okay... I think I've figured out what the problem is! Can you try rebuilding but DONT use UPX. Leave the "UPX Packer Directory" field blank. I think there's some kind of strange issue with UPX at the moment. Can you let me know if this makes a difference? thanks

**Comment by sithis993** [comment] 2017-10-13 15:30
Fairly confident this is the problem here. Issue #32  was exactly the same and was fixed by not using the UPX packer. I'll get this fixed so that UPX can be used ASAP

**Comment by Dontmindmes** [comment] 2017-10-13 16:04
Hey hi, 
when u built the .exe i had upx disabled

**Comment by sithis993** [comment] 2017-10-13 16:14
Are you able to post the output of the Builder console?

**Comment by sithis993** [comment] 2017-10-13 23:08
So I think this problem is actually a combination of two things: UPX and an issue with wxPython version 3.0.0.0. I've since updated the distributable to use a newer version of wxPython which has fixed this problem. Please redownload the Crypter_distributable_2.0.zip package from [here](https://github.com/sithis993/Crypter/releases/tag/2.0) and let me know how that goes :-)

**Comment by Dontmindmes** [comment] 2017-10-14 00:17
I am using your package XD

**Comment by sithis993** [comment] 2017-10-14 07:33
I have updated it several times though in the last few days (including when I posted my last comment), so you may have an older release. The new package has the correct version of wxPython (3.0.2.0)

**Comment by sithis993** [comment] 2017-10-17 22:23
Closed due to inactivity/assuming this is fixed given your responses to other issues

**Closed by sithis993** 2017-10-17 22:23 UTC
