### ISSUE TITLE
Make it non resize able? BUG FOUND

### ISSUE THREAD

**Issue by Dontmindmes** [sithis993/Crypter#43] opened 2017-10-19 22:26 UTC
https://gyazo.com/b225747157a8918cf264cb5bf0956794

And possible to make it always on top.

BTW is it possible to desgin a flat ui for it? (i have a ui i coded in C#)

BUG: https://gyazo.com/f2d7f325b2d7519e0b3e2fe89a4dc293

**Comment by sithis993** [comment] 2017-10-20 08:49
Hey, I actually made the change in this release so that it was resizeable hahaha. The reason was because I had seen tests in certain environments where the interface/font size was too large, and this would cause the Buttons at the bottom to not be visible, or to squash down so that you could see them, but the text wasn't readable. 

This, combined with not being able to resize the interface was pretty gamebreaking, and would mean you couldn't decrypt your files. Consequently, I made the interface slightly bigger, and then added the option to make it resizeable in case it was bigger than the screen. If you think for example of running a Windows machine in VMware without VMware tools, the screen size is usually very small.

However, this as well as the _always on top_ thing is down to personal preference, and also the environments you're running it on/machines you're targeting. Consequently, I think it makes sense to use the Builder here and add options for both of these. It would probably need another two checkboxes, one for "Make GUI Resizeable" and one for "Always on top". This should be pretty straightforward :-)  I'll start working on this and post any updates here.

I'm actually not a GUI guy by trade.... and Crypter has been my first real attempt at creating a Graphical User Interface. Can you explain what you mean here by flat UI? perhaps an example or an idea of the difference between this and my current design.

Regarding the bug.. I can't quite see what the problem is, and I don't have any experience with Sandboxie I'm afraid. Is this because the executable is too large? this looks like a problem specific to Sandboxie, not necessarily to Crypter.

**Comment by sithis993** [comment] 2017-10-20 14:21
Implemented this functionality, along with some other cool stuff you can see directly below it:

![image](https://user-images.githubusercontent.com/22727993/31824896-63284dbc-b5a8-11e7-9d92-63849b1a130b.png)

With these checkboxes you can choose whether to allow the GUI to be resized, and whether to keep the GUI on top of all other windows. Additionally, the colour pickers can be used to customise the look of the GUI. For example:

![image](https://user-images.githubusercontent.com/22727993/31825010-b96cda9e-b5a8-11e7-9440-9020f285b716.png)

It's not in the repository yet however. Needs some more testing but should have it in over the weekend.

**Comment by Dontmindmes** [comment] 2017-10-20 17:59
The bug i found was when no none of the encrypt files are enabled and the gui just shows it starts to opens all the proccess

**Comment by Dontmindmes** [comment] 2017-10-20 18:00
by flat ui i mean material ui somthing that looks nice

https://gyazo.com/3ce1035931f9aa87101fc32804872d9a

**Comment by sithis993** [comment] 2017-10-22 13:18
Sorry, what do you mean by _it starts to open all the processes_?

I see what you mean by flat UI. I think the way the GUI looks is a limitation of wxPython/wxWidgets. I'm not so sure it's possible to create, shall we say _unique_, looking UIs. I suspect that by using a specific GUI framework (wxWidgets, QT, etc.) you are limited to its capabilities, and what you are able to create will still feel and look like the same framework.

It's a bit like programming on top of a specific game engine. You are restricted to that engine's capabilities. I may be wrong here however... I'll do some research :-)

**Comment by sithis993** [comment] 2017-10-22 13:20
On a related note, I actually plan on adding a _stealth mode_ option to the Builder which will exclude the entire GUI and instead display something like a JPEG image, by changing the wallpaper for example. The advantage of this that it will cut the filesize by more than half. Bundling a GUI is quite a task, which is why the exe is around 7MB in size.

In a real-world scenario, a smaller filesize is usually more important than displaying a cool looking UI.

**Comment by sithis993** [comment] 2017-11-11 21:05
Closing this issue as it has now been solved and included in the new release (2.20). More specifically, Added options in the new release for:
- Making Crypter Window always on top
- Making Crypter window resizeable
- Crypter window background colour
- Crypter window title/heading font colour
- Crypter window primary font colour
- Crypter window secondary font colour
- Created subcategories under builder "Ransomware Settings"
- Numerous bug fixes

**Closed by sithis993** 2017-11-11 21:05 UTC
