### ISSUE TITLE
General Errors

### ISSUE THREAD

**Issue by 73CH9ICH13F** [sithis993/Crypter#62] opened 2018-09-21 19:52 UTC
Hello 
Sorry I got Paypal Problems so I couldn't donate you something I will pay you as soon my problems away. I tested the crypter on a VM and Disable Task Manager didnt work am I doing something wrong ?
Thanks

**Comment by sithis993** [comment] 2018-09-24 08:20
Hey, I need to take a better look at this I think.... I remember adding this feature right before I finished the project/called it a day, so it hasn't been rigorously tested. Nevertheless, it did work, but things like user permissions and different versions of Windows weren't thoroughly tested. If I remember correctly, it doesn't completely disable TM, but it does make it much harder to open/access.

Can you test this:
1. Build Crypter with the disable task manager option ticked
2. Before running Crypter, right click the taskbar in windows. You should see an option for Task Manager. If you click it, task manager should appear. Close it down
3. Now run Crypter and wait for the GUI to appear
4. Right click the taskbar again. The task manager option should be unavailable/greyed out. At least on Windows 7 it is greyed out. This may be slightly different on Windows 10.

**Comment by TechniChief** [comment] 2018-09-26 18:28
1 month ago I found it somehow out like there was something set false in a .py file after i reinstalled it didn't work anymore.

**Comment by sithis993** [comment] 2020-04-26 16:31
I'll be reviewing this soon... it's on my list :-)

**Comment by 73CH9ICH13F** [comment] 2020-04-27 08:22
Glad you‘re back, thank you for the development.

**Comment by 73CH9ICH13F** [comment] 2020-04-28 22:24
I'm having a issue installing the requirement.txt. There's no version 1.18.2 only 1.16.

**Comment by sithis993** [comment] 2020-04-29 07:46
Hey, how are you currently finding version 1.16? I've just checked and the latest stable release is 1.18.2, which is what's on PyPi. I've just realised I've made a mistake in the README which I'm about to correct. 

I'm not sure if you've already tried this, but you should install the dependencies from the requirements.txt using "pip install -r requirements.txt" (I missed the **install** bit in the README), which should install version 1.18.2 for you

**Comment by 73CH9ICH13F** [comment] 2020-04-29 11:47
I'm getting this error. 
![Unbenannt](https://user-images.githubusercontent.com/30529878/80592552-ecd19980-8a1f-11ea-930d-21db74bb2d57.PNG)

**Comment by sithis993** [comment] 2020-04-29 12:34
Ahhh I see the problem here, you're using Python 2.7 and Numpy must have stopped supporting Python 2.7 with version 1.16.

One of the major upgrades I've made with the Crypter is that it no longer supports Python 2.7. It's now Python 3.6+ only. This brings lots of advantages though and gets the project up to speed. Python 2 is getting closer to End-of-Life. I recommend doing the following, as I'm guessing you're still running the setup you had from the old Crypter:

1. Uninstall Python 2.7
2. Install Python 3.6 or 3.7 (32 bit)
3. Run "pip install -r requirements.txt" again. It should work after this

**Comment by 73CH9ICH13F** [comment] 2020-04-29 16:26
Now I'm getting this error.
![Unbenannt](https://user-images.githubusercontent.com/30529878/80620929-e9053d80-8a46-11ea-8999-bd77252b4366.PNG)

**Comment by sithis993** [comment] 2020-04-29 16:33
Hmm that's odd. Can you try pip installing wheel by running "pip install wheel==0.34.2". Then try again? thanks for your patience with this. I've made quite a lot of changes to the project so I did expect a few small issues at first, but hopefully I can get them ironed out

**Comment by 73CH9ICH13F** [comment] 2020-05-02 16:20
Hey, the problem has been solved with the install of requirements. There's still a problem with starting the ''Builder.pyw''. I can't run it, tried with running with python, but gets error's while building a .exe file.
![Unbenannt](https://user-images.githubusercontent.com/30529878/80869543-7ba11900-8ca1-11ea-9ca4-03046e6cb261.PNG)

**Comment by sithis993** [comment] 2020-05-03 14:36
Hmmm that's odd. So does the builder open correctly? The error only occurs when you're actually building Crypter? What is the error you're getting?

**Comment by 73CH9ICH13F** [comment] 2020-05-03 14:50
I'm getting this error. 
![Unbenannt](https://user-images.githubusercontent.com/30529878/80917283-18c18780-8d5e-11ea-9204-a898267b6192.PNG)

**Comment by sithis993** [comment] 2020-05-04 08:08
I think one of the reasons you might be hitting this error is because you're not using a Python virtual environment. That's fine though, you shouldn't _need_ to use a virtual environment but it does make things easier. 

Nevertheless, this problem is actually caused by a path issue in one of the builder scripts, which I've just fixed in version 3.3. Can you do a pull of the latest changes and try it again? :-)

**Comment by 73CH9ICH13F** [comment] 2020-05-04 08:26
Will do, as soon I have time. And again thank you for the great development. A donation is waiting for you.

**Comment by 73CH9ICH13F** [comment] 2020-05-04 19:17
I'm getting these errors now. Left is without a config, right side with config
![Unbenannt](https://user-images.githubusercontent.com/30529878/81004323-80ee9700-8e4c-11ea-92b3-5a15d9fc9151.png)

**Comment by sithis993** [comment] 2020-05-04 19:53
Hmm clearly I've been making too much use of relative paths haha! thanks for helping me to find these. Will take a look and fix this one ASAP.

**Comment by 73CH9ICH13F** [comment] 2020-05-04 20:04
Sure thing, take your time.

**Comment by sithis993** [comment] 2020-05-06 08:17
Hey, sorry for the delay. I've just fixed this path issue in the latest release (3.4). Can you pull the latest changes down and try it again?

**Comment by 73CH9ICH13F** [comment] 2020-05-06 18:07
Hey, I'm getting now these errors.
![Unbenannt](https://user-images.githubusercontent.com/30529878/81212415-292f6780-8fd5-11ea-8d94-7367a2ff6d51.PNG)

**Comment by sithis993** [comment] 2020-05-06 20:06
Hmmm, I'm not sure what this could be. There must be something going on here with the Windows permissions. Are you using a Python virtual environment? or running the Builder using the system installation of Python? If you're not already, I'd highly recommend downloading and using the PyCharm IDE and then opening Crypter as a PyCharm project. From there you can create a virtual environment and install the required dependencies from the requirements.txt file.

This will your life a lot easier and probably get rid of most of these problems you've encountered :-)

**Comment by 73CH9ICH13F** [comment] 2020-05-06 20:45
Thanks man for the tip. I ran it of PyCharm and it worked flawlessly. Gonna bump you up, if found errors.

**Comment by sithis993** [comment] 2020-05-07 12:54
Awesome! PyCharm is a great IDE for Python and when you combine it with virtualenv it makes it much more enjoyable :-) Sure, I'll close this issue but if anything else comes up feel free to create another. Alternatively you can always DM me on Twitter if you just want to discuss general stuff, and not an issue per se.

**Closed by sithis993** 2020-05-07 12:54 UTC
